### ISSUE TITLE
Color SSNs Utility typo

### ISSUE THREAD

**Issue by 1ndy** [EnzymeFunctionInitiative/efi-web#6]
![image](https://github.com/EnzymeFunctionInitiative/efi-web/assets/33045591/598eb550-bf41-4671-b066-e0ed5de89594)
On the [Enzyme Similarity Tool webpage](https://efi.igb.illinois.edu/efi-est/)'s SSN Utilities -> Color SSNs option, the instructions underneath the upload button say "A Cytoscape-edited SNN can serve as input." Should this say "SSN" instead of "SNN"?

**Comment by nilsoberg** [comment]
It should say “SSN”, yes.


From: Hunter ***@***.***>
Sent: Wednesday, March 13, 2024 12:49 PM
To: EnzymeFunctionInitiative/efi-web ***@***.***>
Cc: Oberg, Nils O ***@***.***>; Assign ***@***.***>
Subject: [EnzymeFunctionInitiative/efi-web] Color SSNs Utility typo (Issue #6)


image.png (view on web)<https://urldefense.com/v3/__https:/github.com/EnzymeFunctionInitiative/efi-web/assets/33045591/598eb550-bf41-4671-b066-e0ed5de89594__;!!DZ3fjg!5mLY_kIu-cx_rV5JlFO3LrBAHZ41z191oz0_HqSZO5h5Zif5Vz0V1dFq5WVG_UPk7q98TRHD_o3kKwIEEZtBfdyAgQ$>
On the Enzyme Similarity Tool webpage<https://efi.igb.illinois.edu/efi-est/>'s SSN Utilities -> Color SSNs option, the instructions underneath the upload button say "A Cytoscape-edited SNN can serve as input." Should this say "SSN" instead of "SNN"?
